# Generated by Django 4.1.3 on 2023-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_takenmeal_alter_goldtoken_tokenexpiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstudent',
            name='breakfast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='takenmeal',
            name='breakfast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='takenmeal',
            name='dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='takenmeal',
            name='lunch',
            field=models.IntegerField(default=0),
        ),
    ]
