# Generated by Django 4.1.3 on 2023-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_alter_registeredstudent_breakfast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('numberOfToken', models.IntegerField()),
            ],
        ),
    ]
