# Generated by Django 4.1.3 on 2023-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
