# Generated by Django 4.1.3 on 2023-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_remove_transactions_timestamp_transactions_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
